/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedSamplesUsersIndexRouteImport } from './routes/_authenticated/samples/users/index'
import { Route as AuthenticatedSamplesTasksIndexRouteImport } from './routes/_authenticated/samples/tasks/index'
import { Route as AuthenticatedSamplesPetsIndexRouteImport } from './routes/_authenticated/samples/pets/index'
import { Route as AuthenticatedSamplesChatsIndexRouteImport } from './routes/_authenticated/samples/chats/index'
import { Route as AuthenticatedSamplesAppsIndexRouteImport } from './routes/_authenticated/samples/apps/index'
import { Route as AuthenticatedSamplesPetsNewRouteImport } from './routes/_authenticated/samples/pets/new'
import { Route as AuthenticatedSamplesPetsIdRouteImport } from './routes/_authenticated/samples/pets/$id'
import { Route as AuthenticatedSamplesPetsIdEditRouteImport } from './routes/_authenticated/samples/pets/$id.edit'

const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamplesUsersIndexRoute =
  AuthenticatedSamplesUsersIndexRouteImport.update({
    id: '/samples/users/',
    path: '/samples/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamplesTasksIndexRoute =
  AuthenticatedSamplesTasksIndexRouteImport.update({
    id: '/samples/tasks/',
    path: '/samples/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamplesPetsIndexRoute =
  AuthenticatedSamplesPetsIndexRouteImport.update({
    id: '/samples/pets/',
    path: '/samples/pets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamplesChatsIndexRoute =
  AuthenticatedSamplesChatsIndexRouteImport.update({
    id: '/samples/chats/',
    path: '/samples/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamplesAppsIndexRoute =
  AuthenticatedSamplesAppsIndexRouteImport.update({
    id: '/samples/apps/',
    path: '/samples/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamplesPetsNewRoute =
  AuthenticatedSamplesPetsNewRouteImport.update({
    id: '/samples/pets/new',
    path: '/samples/pets/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamplesPetsIdRoute =
  AuthenticatedSamplesPetsIdRouteImport.update({
    id: '/samples/pets/$id',
    path: '/samples/pets/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSamplesPetsIdEditRoute =
  AuthenticatedSamplesPetsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSamplesPetsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/samples/pets/$id': typeof AuthenticatedSamplesPetsIdRouteWithChildren
  '/samples/pets/new': typeof AuthenticatedSamplesPetsNewRoute
  '/samples/apps/': typeof AuthenticatedSamplesAppsIndexRoute
  '/samples/chats/': typeof AuthenticatedSamplesChatsIndexRoute
  '/samples/pets/': typeof AuthenticatedSamplesPetsIndexRoute
  '/samples/tasks/': typeof AuthenticatedSamplesTasksIndexRoute
  '/samples/users/': typeof AuthenticatedSamplesUsersIndexRoute
  '/samples/pets/$id/edit': typeof AuthenticatedSamplesPetsIdEditRoute
}
export interface FileRoutesByTo {
  '/offline': typeof OfflineRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/samples/pets/$id': typeof AuthenticatedSamplesPetsIdRouteWithChildren
  '/samples/pets/new': typeof AuthenticatedSamplesPetsNewRoute
  '/samples/apps': typeof AuthenticatedSamplesAppsIndexRoute
  '/samples/chats': typeof AuthenticatedSamplesChatsIndexRoute
  '/samples/pets': typeof AuthenticatedSamplesPetsIndexRoute
  '/samples/tasks': typeof AuthenticatedSamplesTasksIndexRoute
  '/samples/users': typeof AuthenticatedSamplesUsersIndexRoute
  '/samples/pets/$id/edit': typeof AuthenticatedSamplesPetsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/offline': typeof OfflineRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/samples/pets/$id': typeof AuthenticatedSamplesPetsIdRouteWithChildren
  '/_authenticated/samples/pets/new': typeof AuthenticatedSamplesPetsNewRoute
  '/_authenticated/samples/apps/': typeof AuthenticatedSamplesAppsIndexRoute
  '/_authenticated/samples/chats/': typeof AuthenticatedSamplesChatsIndexRoute
  '/_authenticated/samples/pets/': typeof AuthenticatedSamplesPetsIndexRoute
  '/_authenticated/samples/tasks/': typeof AuthenticatedSamplesTasksIndexRoute
  '/_authenticated/samples/users/': typeof AuthenticatedSamplesUsersIndexRoute
  '/_authenticated/samples/pets/$id/edit': typeof AuthenticatedSamplesPetsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offline'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/help-center/'
    | '/settings/'
    | '/samples/pets/$id'
    | '/samples/pets/new'
    | '/samples/apps/'
    | '/samples/chats/'
    | '/samples/pets/'
    | '/samples/tasks/'
    | '/samples/users/'
    | '/samples/pets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/offline'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/help-center'
    | '/settings'
    | '/samples/pets/$id'
    | '/samples/pets/new'
    | '/samples/apps'
    | '/samples/chats'
    | '/samples/pets'
    | '/samples/tasks'
    | '/samples/users'
    | '/samples/pets/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/offline'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/samples/pets/$id'
    | '/_authenticated/samples/pets/new'
    | '/_authenticated/samples/apps/'
    | '/_authenticated/samples/chats/'
    | '/_authenticated/samples/pets/'
    | '/_authenticated/samples/tasks/'
    | '/_authenticated/samples/users/'
    | '/_authenticated/samples/pets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples/users/': {
      id: '/_authenticated/samples/users/'
      path: '/samples/users'
      fullPath: '/samples/users/'
      preLoaderRoute: typeof AuthenticatedSamplesUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples/tasks/': {
      id: '/_authenticated/samples/tasks/'
      path: '/samples/tasks'
      fullPath: '/samples/tasks/'
      preLoaderRoute: typeof AuthenticatedSamplesTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples/pets/': {
      id: '/_authenticated/samples/pets/'
      path: '/samples/pets'
      fullPath: '/samples/pets/'
      preLoaderRoute: typeof AuthenticatedSamplesPetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples/chats/': {
      id: '/_authenticated/samples/chats/'
      path: '/samples/chats'
      fullPath: '/samples/chats/'
      preLoaderRoute: typeof AuthenticatedSamplesChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples/apps/': {
      id: '/_authenticated/samples/apps/'
      path: '/samples/apps'
      fullPath: '/samples/apps/'
      preLoaderRoute: typeof AuthenticatedSamplesAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples/pets/new': {
      id: '/_authenticated/samples/pets/new'
      path: '/samples/pets/new'
      fullPath: '/samples/pets/new'
      preLoaderRoute: typeof AuthenticatedSamplesPetsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples/pets/$id': {
      id: '/_authenticated/samples/pets/$id'
      path: '/samples/pets/$id'
      fullPath: '/samples/pets/$id'
      preLoaderRoute: typeof AuthenticatedSamplesPetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/samples/pets/$id/edit': {
      id: '/_authenticated/samples/pets/$id/edit'
      path: '/edit'
      fullPath: '/samples/pets/$id/edit'
      preLoaderRoute: typeof AuthenticatedSamplesPetsIdEditRouteImport
      parentRoute: typeof AuthenticatedSamplesPetsIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSamplesPetsIdRouteChildren {
  AuthenticatedSamplesPetsIdEditRoute: typeof AuthenticatedSamplesPetsIdEditRoute
}

const AuthenticatedSamplesPetsIdRouteChildren: AuthenticatedSamplesPetsIdRouteChildren =
  {
    AuthenticatedSamplesPetsIdEditRoute: AuthenticatedSamplesPetsIdEditRoute,
  }

const AuthenticatedSamplesPetsIdRouteWithChildren =
  AuthenticatedSamplesPetsIdRoute._addFileChildren(
    AuthenticatedSamplesPetsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedSamplesPetsIdRoute: typeof AuthenticatedSamplesPetsIdRouteWithChildren
  AuthenticatedSamplesPetsNewRoute: typeof AuthenticatedSamplesPetsNewRoute
  AuthenticatedSamplesAppsIndexRoute: typeof AuthenticatedSamplesAppsIndexRoute
  AuthenticatedSamplesChatsIndexRoute: typeof AuthenticatedSamplesChatsIndexRoute
  AuthenticatedSamplesPetsIndexRoute: typeof AuthenticatedSamplesPetsIndexRoute
  AuthenticatedSamplesTasksIndexRoute: typeof AuthenticatedSamplesTasksIndexRoute
  AuthenticatedSamplesUsersIndexRoute: typeof AuthenticatedSamplesUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedSamplesPetsIdRoute: AuthenticatedSamplesPetsIdRouteWithChildren,
  AuthenticatedSamplesPetsNewRoute: AuthenticatedSamplesPetsNewRoute,
  AuthenticatedSamplesAppsIndexRoute: AuthenticatedSamplesAppsIndexRoute,
  AuthenticatedSamplesChatsIndexRoute: AuthenticatedSamplesChatsIndexRoute,
  AuthenticatedSamplesPetsIndexRoute: AuthenticatedSamplesPetsIndexRoute,
  AuthenticatedSamplesTasksIndexRoute: AuthenticatedSamplesTasksIndexRoute,
  AuthenticatedSamplesUsersIndexRoute: AuthenticatedSamplesUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  OfflineRoute: OfflineRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
